---
- hosts: all
  become: yes
  roles:
    - geerlingguy.nodejs
    - wtanaka.gcloud_sdk
  tasks:
    - apt:
        name: tig
    # sample mnemonic - no not use for actual transfers
    - copy:
        dest: /etc/environment
        content: |
          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/vagrant"
          NODE_ENV="development"
    - lineinfile:
        path: /home/vagrant/.bashrc
        line: cd /vagrant; shopt -s histappend;
    - name: make aliases
      copy:
        dest: /home/vagrant/.bash_aliases
        content: |
          alias g='gcloud'
    - npm:
        path: /vagrant/
    - command: ps aux
      register: forever_list
    - command: /usr/local/lib/npm/bin/forever start -o /vagrant/logs/main.log /vagrant/main.json
      when: "forever_list.stdout.find('monitor main.js') == -1"
