---
- hosts: all
  become: yes
  roles:
    - geerlingguy.nodejs
    - wtanaka.gcloud_sdk
  tasks:
    - apt:
        name: tig
    - copy:
        dest: /etc/environment
        content: |
          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/vagrant"
    - npm:
        path: /vagrant/
