---
- hosts: all
  gather_facts: yes
  vars:
    service_account_file: /vagrant/auth.json
    authjson: "{{ lookup('file', service_account_file) | from_json }}"
    authkind: serviceaccount
  tasks:
    - pip:
        name: [ requests, google-auth, boto]
    - stat:
        path: /vagrant/auth.json
      register: json_auth_file
      tags: [ always ]
    - debug:
        msg: 'WARNING: ENDING PLAY /vagrant/auth.json not found'
      when: not json_auth_file.stat.exists
    - meta: end_play
      when: not json_auth_file.stat.exists
    - file:
        path: /vagrant/ansible/scripts
        state: directory
    - template:
        src: _setup.sh.j2
        dest: /vagrant/ansible/scripts/setup.sh
        mode: 0760
    - shell: /vagrant/ansible/scripts/setup.sh
      args:
        chdir: /vagrant
      when: deploy is defined and deploy|bool
      tags: [ deploy ]
